## ***AIM - Design and implement a fully connected deep neural network with at least 2 hidden layers for a classification application. Use appropriate Learning Algorithm, output function and loss function.***

## ***Yash Ashok Shirsath BE AI & DS 65 / DL EXP 5***

In [1]:
import tensorflow as tf
from tensorflow.keras import layers, models, optimizers
import numpy as np

In [2]:
np.random.seed(0)
tf.random.set_seed(0)

In [3]:
X_train = np.array([[0.1, 0.2], [0.4, 0.6], [0.5, 0.8], [0.9, 0.7]])
y_train = np.array([0, 1, 1, 2])  # Class labels: 0, 1, or 2

In [4]:
y_train = tf.keras.utils.to_categorical(y_train, 3)

In [5]:
model = models.Sequential([
    layers.Dense(5, activation='relu', input_shape=(2,)),  # Hidden Layer 1 with 5 neurons
    layers.Dense(4, activation='relu'),                   # Hidden Layer 2 with 4 neurons
    layers.Dense(3, activation='softmax')                 # Output Layer with 3 neurons (for 3 classes)
])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [6]:
optimizer = optimizers.SGD(learning_rate=0.1)
model.compile(optimizer=optimizer,
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [7]:
initial_weights = model.get_weights()
print("Initial Weights and Biases:")
for i, weight in enumerate(initial_weights):
    print(f"Weights {i + 1}:\n", weight)

Initial Weights and Biases:
Weights 1:
 [[-0.4782095  -0.34998256 -0.26437116  0.5818349   0.9214212 ]
 [ 0.3038571   0.2144357   0.04062456 -0.40243196 -0.74695534]]
Weights 2:
 [0. 0. 0. 0. 0.]
Weights 3:
 [[ 0.35497105  0.18415856 -0.2605368  -0.43405816]
 [ 0.5758387   0.70091546 -0.6212727  -0.7666468 ]
 [-0.34738088  0.24265182  0.13381106 -0.8091481 ]
 [-0.08264339 -0.7998346   0.3733716  -0.750511  ]
 [ 0.60022426 -0.06584388  0.60498095 -0.4021003 ]]
Weights 4:
 [0. 0. 0. 0.]
Weights 5:
 [[ 0.77636886  0.26059175 -0.20806754]
 [-0.4984723  -0.21537685 -0.00675464]
 [ 0.8806342  -0.6877307   0.0418973 ]
 [ 0.30440676 -0.25365412  0.92158604]]
Weights 6:
 [0. 0. 0.]


In [8]:
num_iterations = 5

for epoch in range(num_iterations):
    # Forward pass to compute predictions
    y_pred = model(X_train)

    # Compute the loss using categorical cross-entropy
    loss_fn = tf.keras.losses.CategoricalCrossentropy()
    loss_value = loss_fn(y_train, y_pred).numpy()

    # Compute the gradients manually using GradientTape
    with tf.GradientTape() as tape:
        y_pred = model(X_train)
        loss_value = loss_fn(y_train, y_pred)

    grads = tape.gradient(loss_value, model.trainable_variables)

    # Update weights using gradient descent
    optimizer.apply_gradients(zip(grads, model.trainable_variables))

    # Print the loss and cost function value for each iteration
    print(f"\nIteration {epoch + 1}, Loss Value: {loss_value}")


Iteration 1, Loss Value: 1.1266063451766968

Iteration 2, Loss Value: 1.1172879934310913

Iteration 3, Loss Value: 1.1088210344314575

Iteration 4, Loss Value: 1.1013492345809937

Iteration 5, Loss Value: 1.0943844318389893


In [9]:
updated_weights = model.get_weights()
print("\nUpdated Weights and Biases after 5 iterations:")
for i, weight in enumerate(updated_weights):
    print(f"Weights {i + 1}:\n", weight)


Updated Weights and Biases after 5 iterations:
Weights 1:
 [[-0.47679725 -0.34859413 -0.26437116  0.5816937   0.87676233]
 [ 0.3068096   0.21736503  0.04062456 -0.4025418  -0.78168994]]
Weights 2:
 [ 0.01668483  0.01693275  0.         -0.00015688 -0.0496209 ]
Weights 3:
 [[ 0.35617158  0.18367028 -0.2605368  -0.43405816]
 [ 0.5767113   0.7005591  -0.6212727  -0.7666468 ]
 [-0.34738088  0.24265182  0.13381106 -0.8091481 ]
 [-0.09876584 -0.7998346   0.36940473 -0.750511  ]
 [ 0.5828686  -0.06584388  0.6005969  -0.4021003 ]]
Weights 4:
 [-0.00696797 -0.02519598 -0.01646969  0.        ]
Weights 5:
 [[ 0.77051944  0.25585335 -0.19747974]
 [-0.49821368 -0.21549895 -0.00689117]
 [ 0.868268   -0.69609004  0.06262276]
 [ 0.30440676 -0.25365412  0.92158604]]
Weights 6:
 [-0.04948383  0.08513352 -0.03564968]
